#include<stdio.h>
	main(){
		printf("*\t \t* *****************");
		printf("\n*\t\t*");
		printf("\n*\t\t*");
		printf("\n*\t\t*");
		printf("\n*\t\t*");
		printf("\n*\t\t*");
		printf("\n*\t\t*");
		printf("\n*********************************");
		printf("\n\t\t*\t\t*");
		printf("\n\t\t*\t\t*");
		printf("\n\t\t*\t\t*");
		printf("\n\t\t*\t\t*");
		printf("\n\t\t*\t\t*");
		printf("\n\t\t*\t\t*");
		printf("\n\t\t*\t\t*");
		printf("\n\t\t*\t\t*");
		printf("\n****************");
	}
